apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: cicd
spec:
  encryptedData:
    .dockerconfigjson: AgCjlVttSFK4HdEgQrurV0bApCmCTD+XesuZHL90ei/yztkSKLRoJNGP7DOmDGfO4zk2r4yApf8GtOV98p7qs9HEdjg8Ig5pMQ1dtRsYvtspQrVDRRnV4F7p0DFO+PQ4deMWn81ODAjLdIhYh+6whbCJyTAgJ30AtSMoH0SMV7WUd19qKw4vBENfyCaEuZXxKUl2LNHdTrIGfSK7ib3uUhU4wYz7ROJRgtl3bDXpBb3p6oa0Jq6uPQboubxtmbKBgxjBxwL0/Wma5/+tqJxmSXtgNvpjuDuuAx6/ToXImYnUl8J0XJApP2wBGMhfxyCOZP0/VQVo6yZsRTVVvE3d+b35kWSnweD5rEnk57dh6nda2w6wpXM01dJ07uNffZvhijfUzx/wi7eKfxX2gYvwHCssq9GzzveV8qzjM3CbJ2i4lXU46l9vFbNhq4AYKJZv5H8y2MjNWiDWAUr2OFjE327FaMiE0jsszRv6JEfpC3tsyKOnftj2yTRhxEdO8r7WmD34FWI3c0raQj9pOxDWWfb14Ni9SNV5WineTb5GfH348W7fifurkyY8Hc1rS4gC5n5Xh8UsuKeA7auDvHhW1NX0hDWfU68XQ6cvfPZDx609V3guD0fCquXQN7poA5m8iRNYmjwe/L+26cFSKAtVt3vEyBlScwMio7/vgAqvVaTWJe2IAgJ1i+UMde5HgWic8+b8FHyE3KbH0H1R68mE+O8Es4TQiwZ3dbCufyrCE0IxcoGVRbbzuT7+PFL+i1K+mNAWFggFIk45zTW2Eupo9jsOONZCy8w/jwxLNckKo7NIlEJyQe5mkX2n3zSiMFJWToK/O4XGxUssyvaxVYY13epDTgEULprfBHzRHqABwg0gT74lfQLqCFlvGfoipSluc4/rAmIHOPMbBKCNZPo3uy87XZIrWvmbHTcpnLOy9lGYciOwAG/FjIxuSBi2zvBP2vTYTgjySJ7efcH4K4Il5diWUsr/FVuNTSjO4ycI456fh+QTv0k8ZIxyJbz+Sx6YIe7au/QvN7zpqED+vV7zs5dywdJLTi9P5S+paA+G+sM0f6CaARWgFHHddjne3U1Ywr0Bl7EAAU1J6r35RpUmBOIcNnvyJSzlxoZcKxPNV1ltfqdEO5Ihw32EjvkUC0YH0v5HqiGdNWXo0G2NoQd6hHw8nhTQ6Pk1mlpdk9MZSLv0Gxw5dz7qakZUK1ZtOXXyRKxmMcnhZXB6M9J9xPpxsz67/gZ4gfwstpUdh48ParklZN5sV8hCIIFcQPl1+MExABIBWG4=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: cicd
    type: kubernetes.io/dockerconfigjson
