apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCNQC+aVb8QmNKcSZBPVGbg29d1dON2lObagXE55SE1xeu8QVC5tqXTl8UhoI4SHS7aGPlt+N3tkFhQbRZwrX6inGKLXyxfrLikuYqVAAImcYKrAFaCeNrzyLWHAoqsgQB7TRTJkMzrrF9VnFngvS1iRBSd7cOegiT6uXt7uwGL5AfrDpkfKW3XVpsQ2nb4TJeip7yKVOxTQ3EIMDG0B+dX5sPon9EInBW6qhC8O5Wyz1lRpRhdAG3vtg9PFDdifB1CcvLg+w0UROdg9jl6XgKd3gq7mSXd36+Zx2qA4fpk/u5ge7jbhSfT2Dqn16PITNCcuMApL9Z2DDLLhpaG/nz5XvYJLsG14UeXztms9MYnwuXK5LDAGO0azhFLtyeh42yhgeYBapLGTXKhIybxY9KCFw4D/aS97XbHKGIosau1ohZVE+WWjGW/YvQskkMWf59f64wf2R5Mf3kD1lyG0dNmLTJtbGizwlNMTNNhI+tF8ek2WY+MnAAksQdkyt7YDDYUOrcTUAE6rB7Zy4vUP8nZv4JEDddrwDGmv1FODnapI7j78RFSr1Vxpn7ezxumxd7/oEda6Gp35Xt7dlsRNGa/bSPdNqK2PzMHlLqYw+4TWmY6prXTjtQ2H8R/gJfMTFyYjnQD0N1IpSYqca8ubPSCGmC5xz/1ppn/QQWEPo0XnJQMZqADhZbSRLHABUkpDCR94//P0WousvIttr6L9ssG91czB84=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
